package cn.edu.zuel.common.module;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("blacklist", "id", Blacklist.class);
		arp.addMapping("card", "id", Card.class);
		arp.addMapping("community", "id", Community.class);
		arp.addMapping("feedback", "id", Feedback.class);
		arp.addMapping("file", "id", File.class);
		arp.addMapping("graph", "id", Graph.class);
		arp.addMapping("graph_like", "id", GraphLike.class);
		arp.addMapping("operator_information", "id", OperatorInformation.class);
		arp.addMapping("product_detail", "id", ProductDetail.class);
		arp.addMapping("product_user", "id", ProductUser.class);
		arp.addMapping("session", "id", Session.class);
		arp.addMapping("sys_config", "id", SysConfig.class);
		arp.addMapping("team", "id", Team.class);
		arp.addMapping("team_member", "id", TeamMember.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("user_information", "id", UserInformation.class);
	}
}

