package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseBlacklist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Blacklist extends BaseBlacklist<Blacklist> {
	public static final Blacklist dao = new Blacklist().dao();
}
