package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseCard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Card extends BaseCard<Card> {
	public static final Card dao = new Card().dao();
}
