package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseCommunity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Community extends BaseCommunity<Community> {
	public static final Community dao = new Community().dao();
}
