package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Feedback extends BaseFeedback<Feedback> {
	public static final Feedback dao = new Feedback().dao();
}
