package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseGraph;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Graph extends BaseGraph<Graph> {
	public static final Graph dao = new Graph().dao();
}
