package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseGraphLike;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GraphLike extends BaseGraphLike<GraphLike> {
	public static final GraphLike dao = new GraphLike().dao();
}
