package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Notice extends BaseNotice<Notice> {
	public static final Notice dao = new Notice().dao();
}
