package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseOperatorInformation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OperatorInformation extends BaseOperatorInformation<OperatorInformation> {
	public static final OperatorInformation dao = new OperatorInformation().dao();
}
