package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseProductDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductDetail extends BaseProductDetail<ProductDetail> {
	public static final ProductDetail dao = new ProductDetail().dao();
}
