package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseProductUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductUser extends BaseProductUser<ProductUser> {
	public static final ProductUser dao = new ProductUser().dao();
}
