package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseSession;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Session extends BaseSession<Session> {
	public static final Session dao = new Session().dao();

	public long isExpired(){
		return System.currentTimeMillis()-this.getExpiresTime().longValue();
	}
}
