package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseSysConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysConfig extends BaseSysConfig<SysConfig> {
	public static final SysConfig dao = new SysConfig().dao();
}
