package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseTeamMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TeamMember extends BaseTeamMember<TeamMember> {
	public static final TeamMember dao = new TeamMember().dao();
}
