package cn.edu.zuel.common.module;

import cn.edu.zuel.common.module.base.BaseUserInformation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInformation extends BaseUserInformation<UserInformation> {
	public static final UserInformation dao = new UserInformation().dao();
}
