package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCard<M extends BaseCard<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 银行卡号
	 */
	public void setCardNumber(java.lang.String cardNumber) {
		set("card_number", cardNumber);
	}
	
	/**
	 * 银行卡号
	 */
	public java.lang.String getCardNumber() {
		return getStr("card_number");
	}
	
	/**
	 * 银行卡密码
	 */
	public void setCardPassword(java.lang.String cardPassword) {
		set("card_password", cardPassword);
	}
	
	/**
	 * 银行卡密码
	 */
	public java.lang.String getCardPassword() {
		return getStr("card_password");
	}
	
	/**
	 * 银行卡余额
	 */
	public void setBalance(java.lang.Float balance) {
		set("balance", balance);
	}
	
	/**
	 * 银行卡余额
	 */
	public java.lang.Float getBalance() {
		return getFloat("balance");
	}
	
}
