package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFile<M extends BaseFile<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 文件存储地址 记录文件在服务器上面存储的地址
	 */
	public void setSavedPath(java.lang.String savedPath) {
		set("saved_path", savedPath);
	}
	
	/**
	 * 文件存储地址 记录文件在服务器上面存储的地址
	 */
	public java.lang.String getSavedPath() {
		return getStr("saved_path");
	}
	
	/**
	 * 文件新名称 一般我们会对上传的文件重新命名，重新命名之后的名称需要存储
	 */
	public void setNewName(java.lang.String newName) {
		set("new_name", newName);
	}
	
	/**
	 * 文件新名称 一般我们会对上传的文件重新命名，重新命名之后的名称需要存储
	 */
	public java.lang.String getNewName() {
		return getStr("new_name");
	}
	
	/**
	 * 文件初始名 记录文件在上传的时候最初的名称
	 */
	public void setOriginalName(java.lang.String originalName) {
		set("original_name", originalName);
	}
	
	/**
	 * 文件初始名 记录文件在上传的时候最初的名称
	 */
	public java.lang.String getOriginalName() {
		return getStr("original_name");
	}
	
	/**
	 * 文件远程存储地址 如果文件从远程服务器上面获得的话就需要有该地址
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * 文件远程存储地址 如果文件从远程服务器上面获得的话就需要有该地址
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}
	
	/**
	 * 文件下载次数 记录文件的下载次数，方便进行一些统计
	 */
	public void setDownloadTimes(java.lang.Integer downloadTimes) {
		set("download_times", downloadTimes);
	}
	
	/**
	 * 文件下载次数 记录文件的下载次数，方便进行一些统计
	 */
	public java.lang.Integer getDownloadTimes() {
		return getInt("download_times");
	}
	
	/**
	 * 文件大小 单位:b
	 */
	public void setSize(java.lang.Long size) {
		set("size", size);
	}
	
	/**
	 * 文件大小 单位:b
	 */
	public java.lang.Long getSize() {
		return getLong("size");
	}
	
	/**
	 * 文件来源 文件来源 1-IM 2-其他
	 */
	public void setSource(java.lang.Integer source) {
		set("source", source);
	}
	
	/**
	 * 文件来源 文件来源 1-IM 2-其他
	 */
	public java.lang.Integer getSource() {
		return getInt("source");
	}
	
	/**
	 * 文件类型 文件类型 1-文本文件 2-图片文件 3-音频文件 4-视频文件 5-其他文件
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 文件类型 文件类型 1-文本文件 2-图片文件 3-音频文件 4-视频文件 5-其他文件
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 文件后缀名 后缀名为jpg/png等，无.
	 */
	public void setSuffix(java.lang.String suffix) {
		set("suffix", suffix);
	}
	
	/**
	 * 文件后缀名 后缀名为jpg/png等，无.
	 */
	public java.lang.String getSuffix() {
		return getStr("suffix");
	}
	
}
