package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlacklist<M extends BaseBlacklist<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 用户id 从用户表获得
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户id 从用户表获得
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * 拉黑状态 0-未拉黑；1-已拉黑
	 */
	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	/**
	 * 拉黑状态 0-未拉黑；1-已拉黑
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}
	
	/**
	 * 拉黑原因 用户被拉黑的原因
	 */
	public void setReason(java.lang.String reason) {
		set("reason", reason);
	}
	
	/**
	 * 拉黑原因 用户被拉黑的原因
	 */
	public java.lang.String getReason() {
		return getStr("reason");
	}
	
	/**
	 * 拉黑人id
	 */
	public void setAdminId(java.math.BigInteger adminId) {
		set("admin_id", adminId);
	}
	
	/**
	 * 拉黑人id
	 */
	public java.math.BigInteger getAdminId() {
		return get("admin_id");
	}
	
}
