package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductDetail<M extends BaseProductDetail<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 从用户表中获取配置人员id
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 从用户表中获取配置人员id
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 产品编号 产品编号根据主键id加密得到
	 */
	public void setNumber(java.lang.String number) {
		set("number", number);
	}
	
	/**
	 * 产品编号 产品编号根据主键id加密得到
	 */
	public java.lang.String getNumber() {
		return getStr("number");
	}
	
	/**
	 * 产品名称 产品名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 产品名称 产品名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 产品介绍 产品介绍
	 */
	public void setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
	}
	
	/**
	 * 产品介绍 产品介绍
	 */
	public java.lang.String getIntroduction() {
		return getStr("introduction");
	}
	
	/**
	 * 产品期限 以“天”为单位，活期存款的期限为-1
	 */
	public void setTerm(java.lang.Integer term) {
		set("term", term);
	}
	
	/**
	 * 产品期限 以“天”为单位，活期存款的期限为-1
	 */
	public java.lang.Integer getTerm() {
		return getInt("term");
	}
	
	/**
	 * 年化利率 年化利率
	 */
	public void setAnnualRate(java.lang.Float annualRate) {
		set("annual_rate", annualRate);
	}
	
	/**
	 * 年化利率 年化利率
	 */
	public java.lang.Float getAnnualRate() {
		return getFloat("annual_rate");
	}
	
	/**
	 * 起存金额 起存金额
	 */
	public void setInitialMoney(java.lang.Float initialMoney) {
		set("initial_money", initialMoney);
	}
	
	/**
	 * 起存金额 起存金额
	 */
	public java.lang.Float getInitialMoney() {
		return getFloat("initial_money");
	}
	
	/**
	 * 递增金额 递增金额
	 */
	public void setIncreaseMoney(java.lang.Float increaseMoney) {
		set("increase_money", increaseMoney);
	}
	
	/**
	 * 递增金额 递增金额
	 */
	public java.lang.Float getIncreaseMoney() {
		return getFloat("increase_money");
	}
	
	/**
	 * 单人限额 单人限额
	 */
	public void setPersonalLimit(java.lang.Float personalLimit) {
		set("personal_limit", personalLimit);
	}
	
	/**
	 * 单人限额 单人限额
	 */
	public java.lang.Float getPersonalLimit() {
		return getFloat("personal_limit");
	}
	
	/**
	 * 单日限额 单日限额
	 */
	public void setDailyLimit(java.lang.Float dailyLimit) {
		set("daily_limit", dailyLimit);
	}
	
	/**
	 * 单日限额 单日限额
	 */
	public java.lang.Float getDailyLimit() {
		return getFloat("daily_limit");
	}
	
	/**
	 * 风险等级id 在系统配置表中获取 1-极低；2-低；3-中等；4-较高；5-高
	 */
	public void setRiskId(java.math.BigInteger riskId) {
		set("risk_id", riskId);
	}
	
	/**
	 * 风险等级id 在系统配置表中获取 1-极低；2-低；3-中等；4-较高；5-高
	 */
	public java.math.BigInteger getRiskId() {
		return get("risk_id");
	}
	
	/**
	 * 结息方式 0-到期付息；1-按月付息；2-按年付息；3-按季付息
	 */
	public void setInterestWay(java.lang.Integer interestWay) {
		set("interest_way", interestWay);
	}
	
	/**
	 * 结息方式 0-到期付息；1-按月付息；2-按年付息；3-按季付息
	 */
	public java.lang.Integer getInterestWay() {
		return getInt("interest_way");
	}
	
	/**
	 * 库存量 库存量
	 */
	public void setAmount(java.lang.Integer amount) {
		set("amount", amount);
	}
	
	/**
	 * 库存量 库存量
	 */
	public java.lang.Integer getAmount() {
		return getInt("amount");
	}
	
	/**
	 * 可购买量 可购买量
	 */
	public void setAvailable(java.lang.Integer available) {
		set("available", available);
	}
	
	/**
	 * 可购买量 可购买量
	 */
	public java.lang.Integer getAvailable() {
		return getInt("available");
	}
	
	/**
	 * 销售量 销售量
	 */
	public void setSale(java.lang.Integer sale) {
		set("sale", sale);
	}
	
	/**
	 * 销售量 销售量
	 */
	public java.lang.Integer getSale() {
		return getInt("sale");
	}
	
	/**
	 * 产品状态 0-未发布；1-已提交管理员审核；2-已发布
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 产品状态 0-未发布；1-已提交管理员审核；2-已发布
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 产品正式发布日期 发布日
	 */
	public void setPublishDay(java.util.Date publishDay) {
		set("publish_day", publishDay);
	}
	
	/**
	 * 产品正式发布日期 发布日
	 */
	public java.util.Date getPublishDay() {
		return get("publish_day");
	}
	
	/**
	 * 省名称,用于地域控制
	 */
	public void setRegion(java.lang.String region) {
		set("region", region);
	}
	
	/**
	 * 省名称,用于地域控制
	 */
	public java.lang.String getRegion() {
		return getStr("region");
	}
	
	/**
	 * 存款类型 0-通知存款；1-定期存款
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 存款类型 0-通知存款；1-定期存款
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 存款产品配置人员封面图
	 */
	public void setOperatorCover(java.math.BigInteger operatorCover) {
		set("operator_cover", operatorCover);
	}
	
	/**
	 * 存款产品配置人员封面图
	 */
	public java.math.BigInteger getOperatorCover() {
		return get("operator_cover");
	}
	
	/**
	 * 存款产品用户封面图
	 */
	public void setUserCover(java.math.BigInteger userCover) {
		set("user_cover", userCover);
	}
	
	/**
	 * 存款产品用户封面图
	 */
	public java.math.BigInteger getUserCover() {
		return get("user_cover");
	}
	
}
