package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 用户类型 0-测试用户；1-管理员；2-银行配置人员；3-用户
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 用户类型 0-测试用户；1-管理员；2-银行配置人员；3-用户
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 登录密码 记录登录密码，管理员和银行配置人员的默认密码为123456
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 登录密码 记录登录密码，管理员和银行配置人员的默认密码为123456
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * 加密盐 存储的是密码加密的时候需要的加密盐
	 */
	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}
	
	/**
	 * 加密盐 存储的是密码加密的时候需要的加密盐
	 */
	public java.lang.String getSalt() {
		return getStr("salt");
	}
	
	/**
	 * 手机号码 记录联系方式，用户登录的账号，管理员与配置人员此字段可空
	 */
	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	/**
	 * 手机号码 记录联系方式，用户登录的账号，管理员与配置人员此字段可空
	 */
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}
	
	/**
	 * 工号 管理员与配置人员用工号登录，用户此字段可以为空
	 */
	public void setNumber(java.lang.String number) {
		set("number", number);
	}
	
	/**
	 * 工号 管理员与配置人员用工号登录，用户此字段可以为空
	 */
	public java.lang.String getNumber() {
		return getStr("number");
	}
	
	/**
	 * 头像图片id
	 */
	public void setIconId(java.math.BigInteger iconId) {
		set("icon_id", iconId);
	}
	
	/**
	 * 头像图片id
	 */
	public java.math.BigInteger getIconId() {
		return get("icon_id");
	}
	
}
