package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGraph<M extends BaseGraph<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 产品id 从产品表中获取产品id
	 */
	public void setProductId(java.math.BigInteger productId) {
		set("product_id", productId);
	}
	
	/**
	 * 产品id 从产品表中获取产品id
	 */
	public java.math.BigInteger getProductId() {
		return get("product_id");
	}
	
	/**
	 * json数据 储存前端传来的流程图json数据
	 */
	public void setJsonChart(java.lang.String jsonChart) {
		set("json_chart", jsonChart);
	}
	
	/**
	 * json数据 储存前端传来的流程图json数据
	 */
	public java.lang.String getJsonChart() {
		return getStr("json_chart");
	}
	
	/**
	 * json数据 储存处理前端传来的流程图json数据，便于后续流程判断
	 */
	public void setDealJson(java.lang.String dealJson) {
		set("deal_json", dealJson);
	}
	
	/**
	 * json数据 储存处理前端传来的流程图json数据，便于后续流程判断
	 */
	public java.lang.String getDealJson() {
		return getStr("deal_json");
	}
	
	/**
	 * 配置人员id 对应用户表中配置人员id，创建该流程图的配置人员
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 配置人员id 对应用户表中配置人员id，创建该流程图的配置人员
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * 图片base64数据方式
	 */
	public void setImg(java.lang.String img) {
		set("img", img);
	}
	
	/**
	 * 图片base64数据方式
	 */
	public java.lang.String getImg() {
		return getStr("img");
	}
	
}
