package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGraphLike<M extends BaseGraphLike<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 模板id 从community表中获取模板id
	 */
	public void setGraphId(java.math.BigInteger graphId) {
		set("graph_id", graphId);
	}
	
	/**
	 * 模板id 从community表中获取模板id
	 */
	public java.math.BigInteger getGraphId() {
		return get("graph_id");
	}
	
	/**
	 * 配置人员id 从user表中获取
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 配置人员id 从user表中获取
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * 区分点赞和收藏 0-点赞；1-收藏
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 区分点赞和收藏 0-点赞；1-收藏
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
}
