package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductUser<M extends BaseProductUser<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间（订单生成时间）
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间（订单生成时间）
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间 更新时间（付款时间即日志生成时间)
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间（付款时间即日志生成时间)
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 产品id
	 */
	public void setProductId(java.math.BigInteger productId) {
		set("product_id", productId);
	}
	
	/**
	 * 产品id
	 */
	public java.math.BigInteger getProductId() {
		return get("product_id");
	}
	
	/**
	 * 用户id
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户id
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * 购买金额 购买金额
	 */
	public void setAmount(java.lang.Float amount) {
		set("amount", amount);
	}
	
	/**
	 * 购买金额 购买金额
	 */
	public java.lang.Float getAmount() {
		return getFloat("amount");
	}
	
	/**
	 * 关系类型 0-购买未完成；1-购买已完成
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 关系类型 0-购买未完成；1-购买已完成
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 起息日
	 */
	public void setInterestStart(java.util.Date interestStart) {
		set("interest_start", interestStart);
	}
	
	/**
	 * 起息日
	 */
	public java.util.Date getInterestStart() {
		return get("interest_start");
	}
	
	/**
	 * 到期日
	 */
	public void setEndDay(java.util.Date endDay) {
		set("end_day", endDay);
	}
	
	/**
	 * 到期日
	 */
	public java.util.Date getEndDay() {
		return get("end_day");
	}
	
}
