package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFeedback<M extends BaseFeedback<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 反馈人id
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 反馈人id
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * 反馈对象id 用户反馈的是产品ID，配置人员反馈的是配置人员id，管理员反馈的也是配置人员id
	 */
	public void setObjectId(java.math.BigInteger objectId) {
		set("object_id", objectId);
	}
	
	/**
	 * 反馈对象id 用户反馈的是产品ID，配置人员反馈的是配置人员id，管理员反馈的也是配置人员id
	 */
	public java.math.BigInteger getObjectId() {
		return get("object_id");
	}
	
	/**
	 * 反馈内容 反馈的具体内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 反馈内容 反馈的具体内容
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	/**
	 * 反馈类型 0-用户向配置人员反馈；1-配置人员向管理员反馈；2-管理员给配置人员发消息
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 反馈类型 0-用户向配置人员反馈；1-配置人员向管理员反馈；2-管理员给配置人员发消息
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 反馈信息状态 0-未查看/配置人员未读，1-正在解决/配置人员已读，2-已解决（自动跳转到发布公告页面）3.管理员进行删除
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 反馈信息状态 0-未查看/配置人员未读，1-正在解决/配置人员已读，2-已解决（自动跳转到发布公告页面）3.管理员进行删除
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
}
