package cn.edu.zuel.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserInformation<M extends BaseUserInformation<M>> extends Model<M> implements IBean {

	/**
	 * 主键 自增主键
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 自增主键
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 用户id 记录用户id，对应用户表中用户id
	 */
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	/**
	 * 用户id 记录用户id，对应用户表中用户id
	 */
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	/**
	 * 真实姓名 记录用户姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 真实姓名 记录用户姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 身份证号 记录用户身份证号
	 */
	public void setNumber(java.lang.String number) {
		set("number", number);
	}
	
	/**
	 * 身份证号 记录用户身份证号
	 */
	public java.lang.String getNumber() {
		return getStr("number");
	}
	
	/**
	 * 性别 0-男；1-女
	 */
	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}
	
	/**
	 * 性别 0-男；1-女
	 */
	public java.lang.Integer getGender() {
		return getInt("gender");
	}
	
	/**
	 * 民族 记录用户的民族
	 */
	public void setNation(java.lang.String nation) {
		set("nation", nation);
	}
	
	/**
	 * 民族 记录用户的民族
	 */
	public java.lang.String getNation() {
		return getStr("nation");
	}
	
	/**
	 * 出生日期 用户出生日期
	 */
	public void setBirth(java.util.Date birth) {
		set("birth", birth);
	}
	
	/**
	 * 出生日期 用户出生日期
	 */
	public java.util.Date getBirth() {
		return get("birth");
	}
	
	/**
	 * 住址 用户住址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	/**
	 * 住址 用户住址
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	/**
	 * 银行卡号 用户银行卡号
	 */
	public void setCardNumber(java.lang.String cardNumber) {
		set("card_number", cardNumber);
	}
	
	/**
	 * 银行卡号 用户银行卡号
	 */
	public java.lang.String getCardNumber() {
		return getStr("card_number");
	}
	
	/**
	 * 银行卡密码 用户银行卡密码
	 */
	public void setCardPassword(java.lang.String cardPassword) {
		set("card_password", cardPassword);
	}
	
	/**
	 * 银行卡密码 用户银行卡密码
	 */
	public java.lang.String getCardPassword() {
		return getStr("card_password");
	}
	
	/**
	 * 用户标签id 1-保守型；2-稳健型；3-平衡型；4-成长型；5-进取型
	 */
	public void setTagId(java.math.BigInteger tagId) {
		set("tag_id", tagId);
	}
	
	/**
	 * 用户标签id 1-保守型；2-稳健型；3-平衡型；4-成长型；5-进取型
	 */
	public java.math.BigInteger getTagId() {
		return get("tag_id");
	}
	
	/**
	 * 身份证签发机关 身份证反面识别
	 */
	public void setAuthority(java.lang.String authority) {
		set("authority", authority);
	}
	
	/**
	 * 身份证签发机关 身份证反面识别
	 */
	public java.lang.String getAuthority() {
		return getStr("authority");
	}
	
	/**
	 * 身份证签发日期 身份证反面识别
	 */
	public void setSignDate(java.util.Date signDate) {
		set("sign_date", signDate);
	}
	
	/**
	 * 身份证签发日期 身份证反面识别
	 */
	public java.util.Date getSignDate() {
		return get("sign_date");
	}
	
	/**
	 * 身份证到期日期 身份证反面识别
	 */
	public void setFinalDate(java.util.Date finalDate) {
		set("final_date", finalDate);
	}
	
	/**
	 * 身份证到期日期 身份证反面识别
	 */
	public java.util.Date getFinalDate() {
		return get("final_date");
	}
	
	/**
	 * 身份证头像照片，以base64 编码存储
	 */
	public void setHeadPhoto(java.lang.String headPhoto) {
		set("head_photo", headPhoto);
	}
	
	/**
	 * 身份证头像照片，以base64 编码存储
	 */
	public java.lang.String getHeadPhoto() {
		return getStr("head_photo");
	}
	
	/**
	 * 用户注册时上传拍摄的照片id
	 */
	public void setNewlyHead(java.math.BigInteger newlyHead) {
		set("newly_head", newlyHead);
	}
	
	/**
	 * 用户注册时上传拍摄的照片id
	 */
	public java.math.BigInteger getNewlyHead() {
		return get("newly_head");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-没有删除；1-已经删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
}
